package com.suivialimentation.android.ui.mealentry

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.suivialimentation.android.data.ha.HomeAssistantCommandException
import com.suivialimentation.android.data.model.CiqualFoodCandidate
import com.suivialimentation.android.data.model.Meal
import com.suivialimentation.android.data.model.MealItem
import com.suivialimentation.android.data.model.NutrientSnapshot
import com.suivialimentation.android.data.model.OffProductCandidate
import com.suivialimentation.android.data.model.PersonalFoodCandidate
import com.suivialimentation.android.data.model.PortionOption
import com.suivialimentation.android.data.repository.MealWithItems
import com.suivialimentation.android.data.repository.NutritionRepository
import com.suivialimentation.android.data.repository.QuickFood
import java.util.Locale
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

data class FoodChoice(val foodId: String? = null, val sourceType: String, val sourceExternalId: String, val label: String, val nutrientsPer100g: NutrientSnapshot?, val nutrientsPerUnit: NutrientSnapshot? = null, val servingDefinitions: List<PortionOption> = emptyList())
data class MealEntryUiState(val profileId: String, val localDate: String, val mealType: String? = null, val draftMeal: Meal? = null, val items: List<MealItem> = emptyList(), val query: String = "", val searchResults: List<CiqualFoodCandidate> = emptyList(), val personalSearchResults: List<PersonalFoodCandidate> = emptyList(), val searchAttempted: Boolean = false, val searchedQuery: String? = null, val effectiveSearchQuery: String? = null, val selectedFood: FoodChoice? = null, val selectedPortionId: String? = null, val quantityText: String = "", val barcodeText: String = "", val barcodeProduct: OffProductCandidate? = null, val barcodeSearching: Boolean = false, val favoriteFoods: List<QuickFood> = emptyList(), val recentFoods: List<QuickFood> = emptyList(), val quickFoodsLoading: Boolean = true, val searching: Boolean = false, val mutating: Boolean = false, val error: String? = null, val validated: Boolean = false, val pendingExistingMeal: MealWithItems? = null, val editingItem: MealItem? = null, val editQuantityText: String = "")

class MealEntryViewModel(private val repository: NutritionRepository, profileId: String, localDate: String, initialDraft: MealWithItems?, private val existingMeals: List<MealWithItems>) : ViewModel() {
    private val _state = MutableStateFlow(MealEntryUiState(profileId = profileId, localDate = localDate, mealType = initialDraft?.meal?.mealType, draftMeal = initialDraft?.meal, items = initialDraft?.items.orEmpty()))
    val state: StateFlow<MealEntryUiState> = _state.asStateFlow()
    init { loadQuickFoods() }
    private fun loadQuickFoods() { viewModelScope.launch { try { val q=repository.loadQuickFoods(_state.value.profileId); _state.update { it.copy(favoriteFoods=q.favorites,recentFoods=q.recents,quickFoodsLoading=false) } } catch (_:Throwable) { _state.update { it.copy(quickFoodsLoading=false) } } } }
    fun selectMealType(type:String){ if(_state.value.draftMeal!=null)return; val d=matchingDraftForType(existingMeals,type); if(d!=null){_state.update{it.copy(mealType=type,draftMeal=d.meal,items=d.items,pendingExistingMeal=null,error=null)};return}; _state.update{it.copy(mealType=type,pendingExistingMeal=matchingMealForType(existingMeals,type),error=null)} }
    fun complementExistingMeal(){ val e=_state.value.pendingExistingMeal?:return; viewModelScope.launch{_state.update{it.copy(mutating=true,error=null)};try{val c=repository.startMealCorrection(e.meal.id);_state.update{it.copy(draftMeal=c.meal,items=c.items,pendingExistingMeal=null,mutating=false,error=null)}}catch(t:Throwable){_state.update{it.copy(mutating=false,error=userMessage(t,"Impossible de compléter ce repas."))}}} }
    fun createSeparateMeal(){_state.update{it.copy(pendingExistingMeal=null,error=null)}}; fun cancelExistingMealChoice(){_state.update{it.copy(mealType=null,pendingExistingMeal=null,error=null)}}
    fun updateQuery(v:String){_state.update{it.copy(query=v,searchResults=emptyList(),personalSearchResults=emptyList(),searchAttempted=false,searchedQuery=null,effectiveSearchQuery=null,selectedFood=null,selectedPortionId=null,quantityText="",error=null)}}
    fun search(){val c=_state.value;val q=c.query.trim();if(c.mealType==null){_state.update{it.copy(error="Choisissez d'abord le type de repas.")};return};if(q.length<2){_state.update{it.copy(error="Saisissez au moins deux caractères.")};return};viewModelScope.launch{_state.update{it.copy(searching=true,searchResults=emptyList(),personalSearchResults=emptyList(),searchAttempted=true,searchedQuery=q,effectiveSearchQuery=q,selectedFood=null,quantityText="",error=null)};try{var eq=q;val initial=coroutineScope{val p=async{repository.searchPersonalFoods(c.profileId,q)};val ci=async{repository.searchCiqual(c.profileId,q)};p.await() to ci.await()};var r=initial.second;if(r.isEmpty())for(b in buildBroaderCiqualQueries(q)){val br=repository.searchCiqual(c.profileId,b);if(br.isNotEmpty()){eq=b;r=br;break}};_state.update{it.copy(searching=false,searchResults=r,personalSearchResults=initial.first,effectiveSearchQuery=eq,error=null)}}catch(t:Throwable){_state.update{it.copy(searching=false,error=userMessage(t,"Recherche impossible."))}}}}
    fun updateBarcode(v:String){_state.update{it.copy(barcodeText=v.filter(Char::isDigit).take(14),barcodeProduct=null,error=null)}};fun barcodeScanned(v:String){updateBarcode(v);lookupBarcode()};fun barcodeScanFailed(m:String?){_state.update{it.copy(error=m?.takeIf(String::isNotBlank)?:"Le scanner n'a pas pu démarrer.")}}
    fun lookupBarcode(){val c=_state.value;if(c.mealType==null){_state.update{it.copy(error="Choisissez d'abord le type de repas.")};return};val b=c.barcodeText.filter(Char::isDigit);if(b.length !in 8..14){_state.update{it.copy(error="Le code-barres doit contenir entre 8 et 14 chiffres.")};return};viewModelScope.launch{_state.update{it.copy(barcodeSearching=true,barcodeProduct=null,error=null)};try{val p=repository.getOffProduct(c.profileId,b);_state.update{it.copy(barcodeSearching=false,barcodeProduct=p,error=null)}}catch(t:Throwable){_state.update{it.copy(barcodeSearching=false,error=userMessage(t,"Produit introuvable dans Open Food Facts."))}}}}
    fun selectFood(f:CiqualFoodCandidate){_state.update{it.copy(selectedFood=FoodChoice(sourceType=f.sourceType,sourceExternalId=f.sourceExternalId,label=f.label,nutrientsPer100g=f.nutrientsPer100g,servingDefinitions=f.servingDefinitions),selectedPortionId=null,quantityText="",error=null)}}
    fun selectPersonalFood(f:PersonalFoodCandidate){_state.update{it.copy(selectedFood=FoodChoice(sourceType=f.sourceType,sourceExternalId=f.sourceExternalId,label=f.label,nutrientsPer100g=f.nutrientsPer100g,nutrientsPerUnit=f.nutrientsPerUnit,servingDefinitions=f.servingDefinitions),selectedPortionId=if(f.nutrientsPer100g==null)f.servingDefinitions.firstOrNull()?.id else null,quantityText="",error=null)}}
    fun selectOffProduct(f:OffProductCandidate){_state.update{it.copy(selectedFood=FoodChoice(sourceType=f.sourceType,sourceExternalId=f.sourceExternalId,label=listOfNotNull(f.label,f.brand?.takeIf(String::isNotBlank)).joinToString(" · "),nutrientsPer100g=f.nutrientsPer100g,servingDefinitions=f.servingDefinitions),selectedPortionId=null,quantityText="",error=null)}}
    fun selectQuickFood(q:QuickFood){val f=q.food;_state.update{it.copy(selectedFood=FoodChoice(f.id,f.sourceType,f.sourceExternalId.orEmpty(),f.label,f.nutrientsPer100g,f.nutrientsPerUnit,f.servingDefinitions),selectedPortionId=if(f.nutrientsPer100g==null)f.servingDefinitions.firstOrNull()?.id else null,quantityText="",error=null)}}
    fun toggleFavorite(q:QuickFood){val target=!q.isFavorite;viewModelScope.launch{try{repository.setFavorite(_state.value.profileId,q.food.id,target);val tr:(QuickFood)->QuickFood={if(it.food.id==q.food.id)it.copy(isFavorite=target)else it};_state.update{c->c.copy(favoriteFoods=if(target)(c.favoriteFoods+q.copy(isFavorite=true)).distinctBy{it.food.id}else c.favoriteFoods.filterNot{it.food.id==q.food.id},recentFoods=c.recentFoods.map(tr),error=null)}}catch(t:Throwable){_state.update{it.copy(error=userMessage(t,"Impossible de modifier le favori."))}}}}
    fun selectPortion(id:String?){val s=_state.value.selectedFood?:return;if(id==null&&s.nutrientsPer100g==null)return;if(id!=null&&s.servingDefinitions.none{it.id==id})return;_state.update{it.copy(selectedPortionId=id,quantityText="",error=null)}};fun dismissFood(){_state.update{it.copy(selectedFood=null,selectedPortionId=null,quantityText="",error=null)}};fun updateQuantity(v:String){_state.update{it.copy(quantityText=v.filter{c->c.isDigit()||c==','||c=='.'},error=null)}}
    fun editItem(i:MealItem){if(i.foodRefId==null){_state.update{it.copy(error="Cette ancienne entrée doit être supprimée puis ajoutée de nouveau.")};return};_state.update{it.copy(editingItem=i,editQuantityText=i.quantityValue?.toString().orEmpty(),error=null)}};fun updateEditQuantity(v:String){_state.update{it.copy(editQuantityText=v.filter{c->c.isDigit()||c==','||c=='.'},error=null)}};fun dismissItemEdit(){_state.update{it.copy(editingItem=null,editQuantityText="",error=null)}}
    fun confirmItemEdit(){val c=_state.value;val i=c.editingItem?:return;val m=c.draftMeal?:return;val q=c.editQuantityText.replace(',','.').toDoubleOrNull();if(q==null||q<=0){_state.update{it.copy(error="Indiquez une quantité supérieure à zéro.")};return};viewModelScope.launch{_state.update{it.copy(mutating=true,error=null)};try{val u=repository.updateMealItemQuantity(i.id,q,i.quantityUnit?:"g",i.portionId,i.revision,m.revision);_state.update{it.copy(draftMeal=u.meal,items=it.items.map{e->if(e.id==i.id)u.item else e},editingItem=null,editQuantityText="",mutating=false,error=null)}}catch(t:Throwable){_state.update{it.copy(mutating=false,error=userMessage(t,"Impossible de modifier la quantité."))}}}}
    fun removeItem(i:MealItem){val m=_state.value.draftMeal?:return;viewModelScope.launch{_state.update{it.copy(mutating=true,error=null)};try{val r=repository.removeMealItem(i.id,i.revision,m.revision);_state.update{it.copy(draftMeal=r.meal,items=it.items.filterNot{e->e.id==i.id},mutating=false,error=null)}}catch(t:Throwable){_state.update{it.copy(mutating=false,error=userMessage(t,"Impossible de supprimer l’aliment."))}}}}
    fun addSelectedFood(){val c=_state.value;val s=c.selectedFood?:return;val mt=c.mealType?:return;val q=c.quantityText.replace(',','.').toDoubleOrNull();if(q==null||q<=0){_state.update{it.copy(error="Indiquez une quantité supérieure à zéro.")};return};val p=c.selectedPortionId?.let{id->s.servingDefinitions.firstOrNull{it.id==id}};viewModelScope.launch{_state.update{it.copy(mutating=true,error=null)};try{val fid=s.foodId?:when(s.sourceType){"personal"->repository.importPersonalFood(c.profileId,s.sourceExternalId).food.id;"open_food_facts"->repository.importOffFood(c.profileId,s.sourceExternalId).food.id;else->repository.importCiqualFood(c.profileId,s.sourceExternalId).food.id};var m=_state.value.draftMeal;if(m==null){m=repository.createMeal(c.profileId,mt,c.localDate).meal;_state.update{it.copy(draftMeal=m)}};val a=repository.addFoodToMeal(m.id,fid,q,p?.unitLabel?:"g",p?.id,m.revision);_state.update{it.copy(draftMeal=a.meal,items=it.items+a.item,query="",searchResults=emptyList(),personalSearchResults=emptyList(),searchAttempted=false,searchedQuery=null,effectiveSearchQuery=null,selectedFood=null,selectedPortionId=null,quantityText="",barcodeText="",barcodeProduct=null,mutating=false,error=null)}}catch(t:Throwable){_state.update{it.copy(mutating=false,error=userMessage(t,"Impossible d'ajouter cet aliment."))}}}}
    fun validateMeal(){val c=_state.value;val m=c.draftMeal?:return;if(c.items.isEmpty()){_state.update{it.copy(error="Ajoutez au moins un aliment avant de valider le repas.")};return};viewModelScope.launch{_state.update{it.copy(mutating=true,error=null)};try{val r=repository.validateMeal(m.id,m.revision);_state.update{it.copy(draftMeal=r.meal,mutating=false,validated=true,error=null)}}catch(t:Throwable){_state.update{it.copy(mutating=false,error=userMessage(t,"Impossible de valider le repas."))}}}}
    private fun userMessage(t:Throwable,fallback:String):String { val raw=t.message.orEmpty(); return when { raw.contains("Superseded meal is no longer active",ignoreCase=true) -> "Ce repas a déjà été remplacé par une version plus récente. Revenez à Aujourd’hui et ouvrez de nouveau le repas."; t is HomeAssistantCommandException && t.isConflict -> "Le repas a été modifié ailleurs. Revenez à Aujourd’hui puis ouvrez de nouveau le repas."; raw.isNotBlank() && !raw.contains("superseded",ignoreCase=true) -> raw; else -> fallback } }
    class Factory(private val repository:NutritionRepository,private val profileId:String,private val localDate:String,private val initialDraft:MealWithItems?,private val existingMeals:List<MealWithItems> = emptyList()):ViewModelProvider.Factory{@Suppress("UNCHECKED_CAST")override fun<T:ViewModel>create(modelClass:Class<T>):T{require(modelClass.isAssignableFrom(MealEntryViewModel::class.java));return MealEntryViewModel(repository,profileId,localDate,initialDraft,existingMeals) as T}}
}
internal fun buildBroaderCiqualQueries(query:String):List<String>{val n=query.lowercase(Locale.FRANCE).replace('’','\'');val stop=setOf("de","du","des","la","le","les","un","une","d","l","au","aux","a");return Regex("[\\p{L}\\p{Nd}]+").findAll(n).mapIndexed{i,m->Triple(m.value,m.value.length,i)}.filter{(t)->t.length>=3&&t !in stop}.toList().sortedWith(compareByDescending<Triple<String,Int,Int>>{it.second}.thenBy{it.third}).map{it.first}.distinct().filterNot{it==n.trim()}.take(2)}
internal fun matchingDraftForType(meals:List<MealWithItems>,mealType:String):MealWithItems?=meals.filter{it.meal.status=="draft"&&it.meal.mealType==mealType}.maxByOrNull{it.meal.createdAt}
internal fun matchingMealForType(meals:List<MealWithItems>,mealType:String):MealWithItems?=meals.filter{it.meal.status=="validated"&&it.meal.mealType==mealType}.maxByOrNull{it.meal.createdAt}
